name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Deploy
    runs-on: [self-hosted, Windows, X64]

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_SECRET_VALUE }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login using Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        shell: powershell
        run: |
          az account show

      - name: Terraform Version
        shell: powershell
        run: |
          terraform version

      - name: Terraform Init
        shell: powershell
        run: |
          terraform init

      - name: Terraform Format Check
        shell: powershell
        run: |
          terraform fmt

      - name: Terraform Validate
        shell: powershell
        run: |
          terraform validate

      - name: Terraform Plan
        shell: powershell
        run: |
          terraform plan